INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [6757] using statreload
INFO:     Started server process [6784]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     211.251.169.83:48146 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:48166 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:48169 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:63074 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:63095 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:63100 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:63105 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:5438 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:5457 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:5462 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:5467 - "GET /api/count HTTP/1.1" 200 OK
INFO:     185.180.143.77:38946 - "GET / HTTP/1.1" 404 Not Found
INFO:     134.122.50.244:61953 - "GET / HTTP/1.0" 404 Not Found
WARNING:  StatReload detected file change in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6784]
INFO:     Started server process [7646]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     211.251.169.83:19841 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:19849 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:19854 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:19974 - "GET /api/count HTTP/1.1" 200 OK
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12978] using statreload
INFO:     Started server process [13005]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     211.251.169.83:34760 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:34760 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:37394 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:37393 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:37393 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:38956 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:38959 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:38960 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:38961 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:39617 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:39618 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:39618 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:41926 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:41927 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:42122 - "GET /file/csrf.pdf HTTP/1.1" 200 OK
INFO:     211.251.169.83:42123 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:41927 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:42590 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:49309 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:49310 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:49741 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:49744 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:49749 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:49751 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:49310 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:50612 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:51286 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:51296 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:51296 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:52633 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:56593 - "GET /03.mp4 HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:56593 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:56995 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:56998 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:56998 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:58293 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:59366 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:59382 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:59783 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:59789 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:61635 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:5722 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:63965 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:63977 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:63977 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:6789 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:6790 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:12913 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:12917 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:12919 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:12921 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:14681 - "GET /video/p02.mp4 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 60, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 24, in iterfile
    with open(vid_path, mode="rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'video/p02.mp4'
INFO:     211.251.169.83:14680 - "GET /video/p02.mp4 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 60, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 24, in iterfile
    with open(vid_path, mode="rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'video/p02.mp4'
INFO:     211.251.169.83:15134 - "GET /file/csrf.pgf HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path file/csrf.pgf does not exist.
INFO:     211.251.169.83:15133 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:15133 - "GET /file/csrf.pdf HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
INFO:     52.15.93.37:56290 - "GET / HTTP/1.1" 404 Not Found
INFO:     199.19.224.83:40264 - "GET /console/login/LoginForm.jsp HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:6323 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:6419 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:6451 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:6478 - "GET /api/count HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13005]
INFO:     Started server process [13731]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     89.248.164.165:32910 - "GET http%3A//www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 Not Found
INFO:     110.10.129.175:64449 - "POST /_ignition/execute-solution HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:37844 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:37845 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:43309 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:43311 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:57081 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:57132 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:57158 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:57204 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:59749 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:59832 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:59872 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:59928 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:4408 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:4457 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:4491 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:4507 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:24206 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:24262 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:24297 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:24312 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:8530 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:8579 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:8596 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:8622 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:8812 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:8874 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:8905 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:8929 - "GET /api/count HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13731]
INFO:     Started server process [14228]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     211.251.169.83:17047 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:17104 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:17132 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:17171 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:39008 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:39006 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:14734 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:14797 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:14818 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:14836 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:35811 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:35857 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:35889 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:35912 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:38773 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:38848 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:38881 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:38911 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:51012 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:51085 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51120 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51156 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:13013 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:13066 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:13104 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:13138 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:30334 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:30425 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:30455 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:30486 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:44822 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:44884 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:44907 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:44938 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:26966 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:27047 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:27087 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:27122 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:49924 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:50003 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:50064 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:50105 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:48334 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:48391 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:48432 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:48471 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:54720 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:54795 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:54827 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:54854 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:25815 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:25877 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:25903 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:25927 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:24764 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:24851 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:24894 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:24919 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:19276 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:19366 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:19384 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:19405 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:57844 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:57971 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:58001 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:58017 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:51124 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:51199 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51228 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51256 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:22772 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:22857 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:22896 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:22923 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:47433 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:47521 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:47548 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:47578 - "GET /api/count HTTP/1.1" 200 OK
INFO:     134.122.55.198:39280 - "GET / HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:21834 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:21884 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:21922 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:21949 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:26583 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:26654 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:26676 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:26702 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:30627 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:30701 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:30750 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:30813 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:46400 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:46468 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:46489 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:46510 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:12243 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:12294 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:12322 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:12348 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:28806 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:28863 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:28897 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:28936 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:23340 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:23410 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:23434 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:23466 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:29015 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:29072 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:29093 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:29123 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:14801 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:14848 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:14869 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:14904 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:19986 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:20039 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:20065 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:20113 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:36005 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:36062 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:36119 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:36156 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:7851 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:7920 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:7949 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:7964 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:27192 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:27270 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:27319 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:27344 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:11707 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:11783 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:11806 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:11821 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:58908 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:58963 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:58984 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:59012 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:1683 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:1736 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:1772 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:1794 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:16335 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:16392 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:16439 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:16458 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:40770 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:40835 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:40858 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:40886 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:51529 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:51574 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51601 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51624 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:48594 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:48676 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:48703 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:48732 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:63255 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:63316 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:63400 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:63430 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:5006 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:5072 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:5105 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:5116 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:52661 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:52732 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:52772 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:52841 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:24980 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:25036 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:25049 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:25070 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:34740 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:34801 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:34835 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:34878 - "GET /api/count HTTP/1.1" 200 OK
INFO:     209.141.61.16:51786 - "GET / HTTP/1.0" 404 Not Found
INFO:     85.114.138.106:62565 - "GET / HTTP/1.1" 404 Not Found
INFO:     85.114.138.106:62660 - "GET /HNAP1/ HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:13237 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:13311 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:13329 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:13349 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:41991 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:41994 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:41994 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:40578 - "GET /video/p02.mp4 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 60, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 24, in iterfile
    with open(vid_path, mode="rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'video/p02.mp4'
INFO:     211.251.169.83:40579 - "GET /video/p02.mp4 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 60, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 24, in iterfile
    with open(vid_path, mode="rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'video/p02.mp4'
INFO:     211.251.169.83:60130 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:60133 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:13514 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:50137 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:50138 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:25594 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:32947 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:54331 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:21533 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:51909 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:51923 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51934 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:52366 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:61372 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:61386 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:61395 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:61401 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:10673 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:10689 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:10700 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:10716 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:19088 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:19090 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     121.196.214.192:54542 - "POST /_ignition/execute-solution HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:19090 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:5473 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:5493 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:5504 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:5518 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:13337 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:13336 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:29775 - "GET /video/p02.mp4 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 60, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 24, in iterfile
    with open(vid_path, mode="rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'video/p02.mp4'
INFO:     211.251.169.83:29776 - "GET /video/p02.mp4 HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 60, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 52, in _next
    return next(iterator)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 24, in iterfile
    with open(vid_path, mode="rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'video/p02.mp4'
WARNING:  StatReload detected file change in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14228]
INFO:     Started server process [14699]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     211.251.169.83:58073 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:58088 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:58088 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:60305 - "GET /video/03.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:62249 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:62255 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:44470 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:44473 - "GET /video/01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:50221 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:50221 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:50898 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51438 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:51929 - "GET /file/csrf.pdf HTTP/1.1" 200 OK
INFO:     211.251.169.83:53006 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:53013 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:49042 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:49043 - "GET /video/02.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:57598 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:57610 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:57627 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:57634 - "GET /api/count HTTP/1.1" 200 OK
INFO:     211.251.169.83:3213 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:3214 - "GET /video/p01.mp4 HTTP/1.1" 200 OK
INFO:     211.251.169.83:12400 - "GET /video/p02.mp4 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path video/p02.mp4 does not exist.
INFO:     211.251.169.83:12399 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     211.251.169.83:30476 - "GET /api/cmd HTTP/1.1" 200 OK
INFO:     211.251.169.83:30491 - "GET /api/tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:30500 - "GET /api/new_tip HTTP/1.1" 200 OK
INFO:     211.251.169.83:30510 - "GET /api/count HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14699]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jeonmogeon/projects/HackGame/web/main.py", line 16, in <module>
    async def read_item(request: Request):
NameError: name 'Request' is not defined
WARNING:  StatReload detected file change in 'main.py'. Reloading...
INFO:     Started server process [15589]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path file/down.bat does not exist.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path file/down.bat does not exist.
INFO:     211.251.169.83:21403 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/jeonmogeon/.local/lib/python3.9/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path file/down.bat does not exist.
INFO:     211.251.169.83:21413 - "GET /favicon.ico HTTP/1.1" 404 Not Found
